### ISSUE TITLE
Add support to `\part{Part Title}`

### ISSUE THREAD

**Issue by ZeyuSun** [meluso/UMich_Dissertation_Template#11]
It is common that a thesis has many sections and the author may want to group related chapters into parts. For example:
https://aigen.github.io/files/thesis.pdf
https://tex.stackexchange.com/questions/35782/how-to-split-a-latex-document-using-parts-and-chapters

However, it seems this template does not currently support `\part` level sectioning. In `main.tex`, I added two lines to break the content into two parts:
```latex
%% DOCUMENT AREA
\begin{document}

\part{Intro}
\input{chapters/example_chapter_01}
% Place your additional chapters here using the \input{} command

\part{Methodology}
\input{chapters/example_chapter_99}
```
This results in an error: `LaTeX Error: Something's wrong--perhaps a missing \item.` in `.\output.toc` at line 11, with the message:
```plain
l.11 ...ine {part}{I\hspace {1em}Intro}{1}{part.1}
                                                  %
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.
```
The table of contents of the resulting PDF is messed up:
![image](https://github.com/meluso/UMich_Dissertation_Template/assets/38712452/551a9833-8c75-46c0-b426-93c7b22567b2)

**Comment by meluso** [comment]
Hi ZeyuSun, thanks for reaching out. I'm open to considering this feature, though there are a few things we'd need to address before doing so.

1. Does U-M allow dissertations to have "parts" (specifically) in addition to chapters? To date, I've only seen U-M dissertations use chapters, sections, subsections, etc. That doesn't mean it couldn't have them -- the [handbook](https://rackham.umich.edu/wp-content/uploads/2020/09/dissertation-handbook.pdf) doesn't say either way -- but it hasn't been common to U-M dissertations to date. Each university has specific formatting requirements for dissertations, so I wouldn't recommend referencing a CMU dissertation for what we "should" do here. So if you decide this is _really_ important to you, please confirm with [ScholarSpace](https://umich.libcal.com/appointments/scholarspace) that you can do this for your dissertation.
2. If it's allowed, I'd encourage you to fork the template and see if you can find a way to update `thesis-umich.cls` so that the table of contents and the beginning of chapters are correct. Rackham is _very_ picky about how chapters are labeled in dissertations, so we need to make sure we don't break the template for other students.
3. If you find a way to make this work -- and that doesn't affect the formatting for those who don't want to use parts in their dissertations -- we can absolutely look at integrating it into the template! The goal is to make this as flexible as we can while still ensuring that most people have a seamless experience with their latex dissertations. That's already a tall order, so I do what I can with this template.

Let me know if you have thoughts or questions and we'll go from there! Thanks!

**Comment by ZeyuSun** [comment]
Yes you are right, I don't see "parts" in UM thesis template and handbook. For my thesis, part-level sectioning is a nice feature but not necessary, so I think we can leave it for now. Thank you for considering this!

**Comment by ChengyangHuang** [comment]
I came across this, and just FYI: as of 2025, the UM does not fully allow `\part`, as Latex `\part` would create a new page for part title.

I used `\part` in my draft for a pre-defense check, and it gave this feedback:

> - Table of Contents: Part titles must be in title case--remove the all caps

> - Part titles are not allowed to be on their own page--you must move each part title to the following page
