### ISSUE TITLE
[BUG] Links should be underlined

### ISSUE THREAD

**Issue by bryant1410** [meluso/UMich_Dissertation_Template#15]
**Describe the bug**

According to [the formatting guidelines](https://rackham.umich.edu/navigating-your-degree/formatting-guidelines/#Styling), hyperlink text should be underlined. At least they are not produced for me when I use this template.

**To Reproduce**

Try using this in the template and compiling:

```latex
\url{https://github.com}
```

**Expected behavior**
For it to be blue and underlined, but it's just blue instead.

**Comment by meluso** [comment]
Thanks Bryant. This appears to be a new version of the formatting guidelines (in the past 6 months or so), so it's possible we may run into a few issues as we reconcile with it. I'm looking into this and will resolve the issue ASAP.

**Comment by bryant1410** [comment]
BTW, I tried for like an hour to fix it myself but failed to do so.

**Comment by meluso** [comment]
Sorry to hear that Santiago! This looks like a tricky change unfortunately because Rackham wants hyperlinks to websites underlined but not table of contents items underlined. I'll figure something out. What kind of time frame are you working with? I know dissertation timelines can be tight.

**Comment by bryant1410** [comment]
Thanks for doing this John!! I'll defend on June 3rd, then I guess I'll submit my final version of my thesis by like June 22nd.

Still, I feel like Rackham's not gonna care about this?

**Comment by meluso** [comment]
I'm not sure! They're pretty inconsistent tbh with the really detailed guidelines like this, so sometimes they care and sometimes they don't. I've been maintaining this thing for...5 years now and you're the first to mention it, so they haven't cared yet! 😆

If they didn't catch it in your [pre-defense review](https://secure.rackham.umich.edu/OARD/predef/) (>3 weeks before defense), we have some time.

**Comment by bryant1410** [comment]
Thanks for maintaining this repo!!

**Comment by meluso** [comment]
[UMich_Dissertation_Template__Test_Copy.pdf](https://github.com/meluso/UMich_Dissertation_Template/files/15267824/UMich_Dissertation_Template__Test_Copy.pdf)

Does this look correct? Blue and underlined everywhere but in the tables of contents? (I can't get more "Word-like" underlining unfortunately, but this is close and probably sufficient)

**Comment by bryant1410** [comment]
I see it from Ubuntu's Document Viewer but not from Google Chrome 🤔. Before I was only testing with the latter, maybe that's why I didn't get it to work.

I actually found online that [it could happen with some PDF viewers](https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/hyperref/doc/hyperref-doc.html#x1-520007.23).

**Comment by meluso** [comment]
Hmm, I see. So that tells us that the `hyperref`-only solutions won't work because it allows two types of url links: boxes and colors. As you pointed out, the boxes don't appear on all PDF viewers. I can see the boxes on Firefox and Adobe, but confirmed that neither Chrome nor Edge will display the boxes (which is the solution I linked you to in that PDF...essentially only coloring the bottom edge of the box).

I'm going to try a couple other options, but in the meantime, let's make sure _you're_ set with your dissertation. How many URLs do you have in your document? The short-term work around is opening these in Adobe Acrobat Pro and reforming URLs to underlined font directly there. If you're already past the pre-review, you're set for a while. But it seems this is a new accessibility effort from the formatting guidelines so I'll have to fix it eventually either way.

**Comment by meluso** [comment]
@bryant1410, I found a package that does what we want! Look okay? (see pages x, 2, & 9) Confirmed on Firefox, Adobe, Edge, & Chrome.

[UMich_Dissertation_Template__Test_Copy_(4).pdf](https://github.com/meluso/UMich_Dissertation_Template/files/15270169/UMich_Dissertation_Template__Test_Copy_.4.pdf)

**Comment by bryant1410** [comment]
Yeah, that looks awesome! Thanks!
