### ISSUE TITLE
Request: remove newtxtext & newtxmath font commands from class

### ISSUE THREAD

**Issue by kelly-sovacool** [meluso/UMich_Dissertation_Template#6]
This template requires the newtxtext & newtxmath packages:
https://github.com/meluso/UMich_Dissertation_Template/blob/283a6a640b81647875a0af2163cfe8ff658a27e0/thesis-umich.cls#L158-L160

Which means users cannot select their own font unless they manually edit the class file.
However, Rackham allows a number of fonts such as Arial, Times, Computer Modern, etc.
I propose removing those lines from the class file. Perhaps instead you could show users how they can select an alternative font in `packages.tex`, e.g. after these lines:
https://github.com/meluso/UMich_Dissertation_Template/blob/283a6a640b81647875a0af2163cfe8ff658a27e0/packages.tex#L22-L23

I have a quarto template [here](https://github.com/kelly-sovacool/rackham) which depends on this repo. I was hoping to automatically update my copy of the class file via gh actions, but I can't do that with the font hard-coded as it is.

I'm happy to open a PR for this.

**Comment by meluso** [comment]
Hi Kelly, I'm open to giving users the option to specify their font and I think giving users that option is a good idea! One of my goals for this template is to make it easy to use for folks who aren't very experienced with latex.

So, if we're going to make a visible change that affects everyone's default like this, I'd like to make sure we do two things: (1) create a user friendly, well-commented option for selecting alternative font types in the main.tex file (rather than the packages so it's not hidden), and (2) set the default font to times new roman so the template starts with a widely-accepted font. I think these two design choices could meet both the goals of flexibility while also ensuring usability for less-experienced users.

What are your thoughts? I'm traveling right now so may be a bit delayed in responding, but I would be happy to consider a pull request that meets those criteria, or discuss if you think something else makes more sense. Thanks!


John Meluso (he/they)

Sloan VERSO Postdoctoral Fellow for Systems, Organizations, and Inclusion

Vermont Complex Systems Center at the University of Vermont

***@***.*** | www.johnmeluso.com<http://www.johnmeluso.com/>

________________________________
From: Kelly Sovacool ***@***.***>
Sent: Monday, June 12, 2023 12:07:58 PM
To: meluso/UMich_Dissertation_Template ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [meluso/UMich_Dissertation_Template] Request: remove newtxtext & newtxmath font commands from class (Issue #6)


This template requires the newtxtext & newtxmath packages:
https://github.com/meluso/UMich_Dissertation_Template/blob/283a6a640b81647875a0af2163cfe8ff658a27e0/thesis-umich.cls#L158-L160

Which means users cannot select their own font unless they manually edit the class file.
However, Rackham allows a number of fonts such as Arial, Times, Computer Modern, etc.
I propose removing those lines from the class file. Perhaps instead you could show users how they can select an alternative font in packages.tex, e.g. after these lines:
https://github.com/meluso/UMich_Dissertation_Template/blob/283a6a640b81647875a0af2163cfe8ff658a27e0/packages.tex#L22-L23

I have a quarto template here<https://github.com/kelly-sovacool/rackham> which depends on this repo. I was hoping to automatically update my copy of the class file via gh actions, but I can't do that with the font hard-coded as it is.

I'm happy to open a PR for this.

**Comment by kelly-sovacool** [comment]
I like your design considerations @meluso. I'll try to submit a PR later this week.
